### ISSUE TITLE
Summary of ASP.NET 5 Buildpack Call

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry-community/asp.net5-buildpack#29]
Hi Team,

The below is a summary of the first ASP.NET 5 (Core) Buildpack call. The call was introductory in nature and covered contributor introductions, project status and short-term improvements, I’ve outlined the call notes below:

#### Current status of the ASP.NET 5 Buildpack:
* As the buildpack is using dotnet core version 1.0.0 RC1, the team is waiting on the release of 1.0.0 RC2. The team expects that changes to the buildpacks will need to be made to support the new version, specifically around naming conventions and tooling
* As Microsoft looks to be branding the project as “.NET Core” it may make sense to rename the project to support discoverability
* The team is using Travis CI to execute tests against pull requests

#### Short-term improvements that were discussed:
* The addition of a configuration provider: The Steel Toe project contains an implementation that may satisfy this requirement
* The addition of more sample apps and test fixtures: The Steel Toe project is planning on creating additional sample apps in the near future. There may be an opportunity to cross-pollinate these into the buildpack
* There was interest from the current maintainers to gain a deeper knowledge of rspec by pairing with the goal of increasing test coverage
* Support for integrating with external services: As support for external services in dotnet core is still in the early stage due to the freshness of the ecosystem this is an area we will explore at a later time

#### Improving the end-user experience
* Remote debugging  
* Improved logging

**Comment by sneal** [comment]
:+1: for leveraging Steel Toe. If you find Steel Toe lacking in particular ways, I'd like to hear about it so I can address any issues.
