### ISSUE TITLE
Switch from DNX to .NET cli

### ISSUE THREAD

**Issue by JTLunsford** [cloudfoundry-community/asp.net5-buildpack#30]
DNX is no longer under development(https://github.com/aspnet/dnx). Any bugs discovered in DNX will not be fix. We should move this buildpack to support .NET CLI(https://github.com/dotnet/cli)

**Comment by opiethehokie** [comment]
I agree YurikoEX. We'll do this with any RC2-related updates the buildpack needs.

**Comment by opiethehokie** [comment]
Buildpack uses dotnet CLI now. To continue using DNX as things were, use the "dnx" branch.
