### ISSUE TITLE
The "Building" Section seems incomplete

### ISSUE THREAD

**Issue by schaveyt** [cloudfoundry-community/asp.net5-buildpack#32]
Context:
I am complete noob at building any sort of buildpack, I am a c# developer looking to mess around with cloud foundry. 

Issue:
1. Please indicate that a prerequisite is to have Ruby installed
2. Please indicate that a prerequisite is to have Ruby DevKit installed
3. Please indicate that a prerequisite is to have Git installed
4. The line simply stating "BUNDLE_GEMFILE=cf.Gemfile bundle". I guess on Windows. The needs to be:
>set BUNDLE_GEMFILE=cf.Gemfile
>bundle

**Comment by degrim** [comment]
I agree we probably do need to add some info about prerequisites to the building section.  If you're just looking to play around with using this buildpack to deploy your apps on Cloud Foundry, you should only need to follow the steps in the usage section to deploy.  The buildpack will already take care of downloading dnvm and the dnx toolchain on the Cloud Foundry server for you.

**Comment by opiethehokie** [comment]
@schaveyt if you really need to build the buildpack then you should do it on Linux. I'll add that to the README with the other things you mention, as well as that the building section only applies to cf admins that are going to install the buildpack.
