### ISSUE TITLE
"No kestrel or web command found"

### ISSUE THREAD

**Issue by seanobrienatvirtustreamcom** [cloudfoundry-community/asp.net5-buildpack#34]
The buildpack seems to work fine with a one project solution, where the only project contains a project.json with a properly formed 'commands' section.

e.g.

`  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel",
    "web": "Microsoft.AspNet.Server.Kestrel"
  },`

Once I have several projects under a parent solution as you would in most applications like

root\Donuts.sln
root\manifest.yml
root\global.json
root\src\Donut.Domain\
root\src\Donut.DB\
root\src\Donut.Web\
root\src\Donut.Web\project.json <- with the web/kestrel command

and Donut.Web has dependencies on .DB and .Domain

When I push I get an error like 
`/lib/buildpack/release/releaser.rb:67:in 'get_cfweb_cmd'`
`No kestrel or web command found in src/Donut.Domain (RuntimeError)`

Almost like it's just checking the first sub-directory or first project.json it encounters?

How can I let the buildpack know which project has my web / kestrel command? If I just push from within the .Web directory the build dies because the dependencies won't be pushed up (and of course they wouldn't be available from nuget since I haven't finished anything yet). 

Can I manually instruct cf to run something after building the droplet?

**Comment by seanobrienatvirtustreamcom** [comment]
After experimenting with changing names of the folders, and the last change date I noticed that the build pack tries to find the kestrel command in the last sub-project that had its dependencies restored. The order in which this is happening seems random, it's not alphabetic and not by the folder date. If it were I could at least name my web directory AAAAA or ZZZZZ and have an awful work around.

**Comment by opiethehokie** [comment]
@seanobrienatvirtustreamcom I'll take a look tomorrow and try to get a fix out. Your scenario was supposed to be working. There's a unit test for it, but maybe the sub-project with the project.json is always the last one restored and that's the only reason it passes.

**Comment by opiethehokie** [comment]
Actually I was just thinking that this app with two projects works - https://github.com/watson-developer-cloud/visual-recognition-aspnet

The only obvious difference seems to be that you have more than two projects.

**Comment by seanobrienatvirtustreamcom** [comment]
Fix worked like a charm on an 8 project solution. Thanks for your help. 

`App ******** was started using this command `dnx --project src/******.Web kestrel --server.urls
http://0.0.0.0:${PORT}``
