### ISSUE TITLE
Doesn't work with RC2

### ISSUE THREAD

**Issue by autodidaddict** [cloudfoundry-community/asp.net5-buildpack#41]
Despite the README indicating that it has been tested with RC2, no RC2 applications created using Visual Studio templates or by hand from any known RC2 templates work. For example, if you push an RC2 app (they don't have the "commands" section in project.json), it doesn't override the port, so the application can't bind to the CF-assigned port.

**Comment by autodidaddict** [comment]
I've also tried this from a publish directory, and I end up with similar results - app doesn't listen on the port, I get a 502 bad gateway when hitting the /api/values of the "file -> new -> web api project" template that used to work with RC1.

**Comment by autodidaddict** [comment]
It appears that at the very least the **--server.urls** parameter to **dotnet run** is not being honored (it doesn't get honored locally, either). I have added the following code to my startup to allow port binding and then the buildpack works (but not because its start command is correct):

`
var port = Environment.GetEnvironmentVariable("PORT");
if (String.IsNullOrEmpty(port)) {
    port = "5000";
}

var host = new WebHostBuilder()
    .UseKestrel()
    .UsePorts("http://:" + port)
    ....
    ...
`

**Comment by degrim** [comment]
The templates that worked with RC1 won't work with the Dotnet CLI out of the box, you'll have to update them to work with RC2.  The samples Microsoft provided in their [cli-samples repo](https://github.com/aspnet/cli-samples/) will work with this buildpack but they need a slight modification to the Startup method.  Before the line `var host = new WebHostBuilder()` add these lines:

```
var config = new ConfigurationBuilder()
            .AddCommandLine(args)
            .Build();
```
And then add this line after:
`.UseConfiguration(config)`

You'll also need to add a dependency to project.json:
`"Microsoft.Extensions.Configuration.CommandLine": "1.0.0-rc2-final",`

An example of a project with these changes already made can be found [here](https://github.com/IBM-Bluemix/asp.net5-cloudant) or [here](https://github.com/IBM-Bluemix/asp.net5-helloworld).

I'll get this added to the Readme today.

**Comment by autodidaddict** [comment]
ahh, I tried the AddCommandLine and it didn't compile... because the tooling (including Visual Studio) is utter garbage, it didn't give me any hint as to what needed to be added to the project. I will try this now, and thanks for updating the README.
